name: Github Pages Deploy
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.DEPLOYMENT_TOKEN }}
          deploy-branch: gh-pages
  uploadFTP:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftpserver }}
          username: ${{ secrets.ftpuser }}
          password: ${{ secrets.ftppassword }}
