name: Github Pages Deploy
on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
      - name: Configure git credentials
        uses: OleksiyRudenko/gha-git-credentials@v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Deploy
        run: npm run deploy
